# Array slicing

In [ ]:
# Array slicing of 1-D array

import numpy as np

one_D=np.array([100,200,300,400,500,600,700,800])
print("One_D array is :",one_D)
print("\nThe daimentio of arry is :",one_D.ndim)
print("\n First element of array is:",one_D[0])


In [ ]:
# Slicing of 2-D array

two_D=np.array([[100,200,300,400,500],[600,700,800,900,999]])
print("Two_D array is :\n",two_D)
print("\nThe daimentio of arry is :",two_D.ndim)
print("\n First element of array is:",two_D[0,0])
print("\n First element of array is:",two_D[1,4])

In [37]:
# Slicing of 3-D array
import numpy as np
three_D=np.array([[[10,20,30],[40,50,60],[70,80,90]]])
print(three_D)
print("\nThe Diamention of the Arrya Is:",three_D.ndim)
print("********************************************")
print("Accessing the oth location`s all element:",three_D[0,0])
print("Accessing the 1st location`s all element:",three_D[0,1])
print("Accessing the 2nd location`s all element:",three_D[0,2])
print("********************************************\n")
print("Now accessing the Specific element of array\n")
print("the fifth element of the aaray is L:",three_D[0,1,1])

[[[10 20 30]
  [40 50 60]
  [70 80 90]]]

The Diamention of the Arrya Is: 3
********************************************
Accessing the oth location`s all element: [10 20 30]
Accessing the 1st location`s all element: [40 50 60]
Accessing the 2nd location`s all element: [70 80 90]
********************************************

Now accessing the Specific element of array

the fifth element of the aaray is L: 50


## Negative slicing slicing

In [59]:
# Lets see the negative slicing/indexing  in array 
neg=np.array([10,11,12,13,14,15,16])
print(neg)
print("\nThe diamention of the array is :",neg.ndim)
print("\nPrinting the last element using the negagtive index:",neg[-1])


[10 11 12 13 14 15 16]

The diamention of the array is : 1

Printing the last element using the negagtive index: 16


In [61]:
#step value in slicing array
print(neg[0:7:2])

[10 12 14 16]
