# Joining the array

In [1]:
import numpy as np


In [2]:
# lets take two array
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([12,13,14,15])

In [3]:
# joining th etwo array using np.concatenate
arr = np.concatenate((arr1,arr2))

In [4]:
arr


array([ 1,  2,  3,  4,  5,  6, 12, 13, 14, 15])

In [5]:
#array concatenation using the axis

ax1 = np.array([[11,22,33,44],[55,66,77,88]])
ax2 = np.array([[10,20,30,40],[50,60,70,80]])

ar_1 = np.concatenate((ax1,ax2),axis=1)

print("\nwith axis = 1 result is :\n\n",ar_1)
print("\n*********************************")

ar_0 = np.concatenate((ax1,ax2),axis=0)

print("\nwith axis = 0 result is :\n\n",ar_0)
print("\n*********************************")


with axis = 1 result is :

 [[11 22 33 44 10 20 30 40]
 [55 66 77 88 50 60 70 80]]

*********************************

with axis = 0 result is :

 [[11 22 33 44]
 [55 66 77 88]
 [10 20 30 40]
 [50 60 70 80]]

*********************************


 # joining array using stack function 

### joining array using stack  is same as conacatenation difference is that stacking is done with along new axis


In [6]:
h_arr_1 = np.array(['a','b','c'])
h_arr_2 = np.array(['d','e','f'])

st_arr_1 = np.stack((h_arr_1,h_arr_2),axis=1)
st_arr_1



array([['a', 'd'],
       ['b', 'e'],
       ['c', 'f']], dtype='<U1')

In [7]:
# along axis =0
st_arr_0 = np.stack((h_arr_1,h_arr_2),axis=0)
st_arr_0

array([['a', 'b', 'c'],
       ['d', 'e', 'f']], dtype='<U1')

In [8]:
# hstack function it concatene or join in a row
first = np.array(["man","bana","app"])
second = np.array(["go","na","le"])

hck = np.hstack((first,second))

hck

array(['man', 'bana', 'app', 'go', 'na', 'le'], dtype='<U4')

In [9]:
# now lets see the stackin galong coloumn

first_1 = np.array(["man","bana","app"])
second_2 = np.array(["go","na","le"])

hsck = np.vstack((first_1,second_2))

hsck

array([['man', 'bana', 'app'],
       ['go', 'na', 'le']], dtype='<U4')

In [10]:
# stacking alon g depth.(Stack arrays in sequence depth wise (along third axis).

st1 = np.array([1,2,3])
st2 = np.array([4,5,6])

dep = np.dstack((st1,st2))
dep

array([[[1, 4],
        [2, 5],
        [3, 6]]])

# splitting array


**********************************

The whole array is :
 [1 2 3 4 5 6 7 8 9]

 The splitted arary is :
 [array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

**********************************

splitted array are:
[1 2 3]
[4 5 6]
[7 8 9]
