# Flattening The Array

In [14]:
# If we want single one-D from N-D array then we have to use reshape(-1)
import numpy as np
two_D = np.array([[10,20,30,40],[50,60,70,80]])
print(two_D)
print("\n***********Cross Checking Some Fact***********")
print("\nIt Is A Two Diamention Array. ")
print("Daimention of array is :",two_D.ndim)
print("The type of array is :",type(two_D))

[[10 20 30 40]
 [50 60 70 80]]

***********Cross Checking Some Fact***********

It Is A Two Diamention Array. 
Daimention of array is : 2
The type of array is : <class 'numpy.ndarray'>


In [15]:
# Fattening the array
res = two_D.reshape(-1)
print(res)

[10 20 30 40 50 60 70 80]
