# filtering array

In [1]:
import numpy as np

In [2]:
'''
Getting some element out from exting array and creatin ga new arryay out of them is called filtering the array 
Numpy filters  array using boolean values

'''

'\nGetting some element out from exting array and creatin ga new arryay out of them is called filtering the array \nNumpy filters  array using boolean values\n\n'

In [5]:
# exapmle
arr = np.array([2,4,5,3])
a = [True,False,False,True]

new = arr[a]
new

array([2, 3])

In [8]:
# printing the even numbers from list or array

arr = np.array([1,2,3,4,5,6,7,8,9,11,12,13,14,15,16,17,18,19,20])

# creating an empty list 
lst = []

for i in arr:
    if i%2==0:
        lst.append(True)
    else:
        lst.append(False)
    
print(lst)

new_arr = arr[lst]

new_arr


[False, True, False, True, False, True, False, True, False, False, True, False, True, False, True, False, True, False, True]


array([ 2,  4,  6,  8, 12, 14, 16, 18, 20])

### Other numpy functions


In [9]:
# arange to create array within given range
ar =  np.arange(10)
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
# finding minnimum
print("The minimum elemnt of array is:",ar.min())

The minimum elemnt of array is: 0


In [12]:
# finding minnimum
print("The maximum number in array is:",ar.max())

The maximum number in array is: 9


In [14]:
# The sum of array element
print("The sum of the array elemnt is :",ar.sum())

The sum of the array elemnt is : 45


In [15]:
# creating an array with random element
ran = np.random.rand(3,3)
ran

array([[0.31812572, 0.75356611, 0.0454547 ],
       [0.97272175, 0.05148098, 0.16484055],
       [0.23100794, 0.68247408, 0.13442928]])

In [18]:
# creating unit matrix

uni = np.eye(5,4)
uni

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])