# Numpy array

* numpy is genral purpose array-proccessing package

In [1]:
# lets import the numpy
import numpy as np

In [5]:
# now creating a list 
ls=[10,20,30,40,50]
print(ls)
print(type(ls))

[10, 20, 30, 40, 50]
<class 'list'>


In [9]:
# now converting the list in to numpy array
ar=np.array(ls)
print(ar)
print(type(ar))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [21]:
# multi diamentional array 

my_arr1=[10,20,30]
my_arr2=[40,50,60]
my_arr3=[70,80,90]

my_arr=np.array([my_arr1,my_arr2,my_arr3])

print(my_arr)
print("\n",type(my_arr))
print("\nThe diamention of array is :",my_arr.ndim)

[[10 20 30]
 [40 50 60]
 [70 80 90]]

 <class 'numpy.ndarray'>

The diamention of array is : 2


## Accessing array element

In [33]:
# accesing the element of 1-D array

one_D = np.array([11,22,33,44,55])
print(one_D)
print("third element is a:",one_D[2])
# print(one_D.ndim)

[11 22 33 44 55]
third element is a: 33


In [45]:
# accesing the element of 2-D array
two_D = np.array([[19,29,39,49],[59,69,79,89]])
print(two_D)
print("\nThe fifth element oif the array is:",two_D[1][0])


[[19 29 39 49]
 [59 69 79 89]]

The fifth element oif the array is: 59
