# nditer

In [9]:
# iterating using  nditer means  Each element of an array is visited 

# iterating on 1-D array
import numpy as np
one_D = np.array([10,20,30,40,50,60])
print("\nThe one_Darray is :",one_D)
a = np.nditer(one_D)
for i in a:
    print(i)


The one_Darray is : [10 20 30 40 50 60]
10
20
30
40
50
60


In [13]:
# printing element of 2-D array using nditer

two_D = np.array([[10,20,30],[40,50,60]])
print("THe two_D array is\n",two_D,"\n")

x = np.nditer(two_D)
for y in x:
    print(y)

THe two_D array is
 [[10 20 30]
 [40 50 60]] 

10
20
30
40
50
60


In [19]:
# printing the elelement of Three_D array
three_D = np.array([[[10,20,30],[40,50,60],[70,80,90]]])
print("The three_array is :\n",three_D)
n = np.nditer(three_D)
print(" \nprinting the element of the three_D array")
for i in n:
    print("\n",i)

The three_array is :
 [[[10 20 30]
  [40 50 60]
  [70 80 90]]]
 
printing the element of the three_D array

 10

 20

 30

 40

 50

 60

 70

 80

 90
