# Numpy Arrray Reshaping

### * Reshaping Array means changing the shape of arrray

### * Shape of an arrray is a number of element in each diamention

In [18]:
# converting one-D array in to two-D arrray
import numpy as  np

one_D = np.array([1,2,3,4,5,6,7,8,9])
print(one_D,"\n")
print("Diamention of array is:",one_D.ndim)

print("\n****************************************")

res = one_D.reshape(3,3)
print("Reshaped array is:\n",res)
print("\nthe siamention of array is",res.ndim)
print("\n****************************************")

[1 2 3 4 5 6 7 8 9] 

Diamention of array is: 1

****************************************
Reshaped array is:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

the siamention of array is 2

****************************************


In [31]:
# now 1-d to 3-D 
one_arr = np.array([11,12,13,14,15,16,17,18,19,20,21,22])
print(one_arr)
print("\nThe diamention of array befor converting in to 3-D is :",one_arr.ndim)
result = one_arr.reshape(3,2,2)
print("\n",result)
print("The diamention of converted array is:",result.ndim)

[11 12 13 14 15 16 17 18 19 20 21 22]

The diamention of array befor converting in to 3-D is : 1

 [[[11 12]
  [13 14]]

 [[15 16]
  [17 18]]

 [[19 20]
  [21 22]]]
The diamention of converted array is: 3


In [35]:
# 2-D to 3-D 
two_D_arr = np.array([[10,20,30,40],[50,60,70,80]])
print("Two-D array is:\n",two_D_arr)
cal = two_D_arr.reshape(2,2,2)
print("\n",cal)
print("Daimention of converted array is ",cal.ndim)

Two-D array is:
 [[10 20 30 40]
 [50 60 70 80]]

 [[[10 20]
  [30 40]]

 [[50 60]
  [70 80]]]
Daimention of converted array is  3
