# splitting array

In [1]:
import numpy as np

In [2]:
'''
the array will be divided
    into N equal arrays along axis.  If such a split is not possible,
    an error is raised.

 for this error there is array_split() function

'''

splt = np.array([1,2,3,4,5,6,7,8,9])
print("\n**********************************\n")
print("The whole array is :\n",splt)
print("\n The splitted arary is :\n",np.split(splt,3))
print("\n**********************************\n")
print("splitted array are:")
for i in np.split(splt,3):
    print(i)


**********************************

The whole array is :
 [1 2 3 4 5 6 7 8 9]

 The splitted arary is :
 [array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

**********************************

splitted array are:
[1 2 3]
[4 5 6]
[7 8 9]


In [3]:
# accessing perticular row of splitted array
np.split(splt,3)[0]

array([1, 2, 3])

In [4]:
# lets take a odd diamentionsarray
odd = np.array([10,20,30,40,50,60,70,80,90,99])
newarr = np.array_split(odd,4)
newarr



[array([10, 20, 30]), array([40, 50, 60]), array([70, 80]), array([90, 99])]

In [5]:
# lets print with for loop
for i in newarr:
    print(i)

[10 20 30]
[40 50 60]
[70 80]
[90 99]


In [6]:
# accessin a particular row of the array 
print("third row of the splitted aarray is:",newarr[3])

third row of the splitted aarray is: [90 99]


# Array splitting on 2-D array

In [7]:
two_d = np.array([[10,20,30,40],[50,60,70,80],[21,32,65,45],[78,89,48,49]])
sp = np.split(two_d,4)
print("splitted array are:\n",sp)

splitted array are:
 [array([[10, 20, 30, 40]]), array([[50, 60, 70, 80]]), array([[21, 32, 65, 45]]), array([[78, 89, 48, 49]])]


In [8]:
# lets print them suitably
a=0
for i in sp:
    print(a,"row of the array is--->",i)
    a+=1

0 row of the array is---> [[10 20 30 40]]
1 row of the array is---> [[50 60 70 80]]
2 row of the array is---> [[21 32 65 45]]
3 row of the array is---> [[78 89 48 49]]


In [9]:
# array splittin gon axis
sp1 = np.split(two_d,4,axis=1)
sp1


[array([[10],
        [50],
        [21],
        [78]]),
 array([[20],
        [60],
        [32],
        [89]]),
 array([[30],
        [70],
        [65],
        [48]]),
 array([[40],
        [80],
        [45],
        [49]])]

In [13]:
# array splittin gon axis
a=0
for i in sp1:
    print(a,"colomn is:",i,"\n")
    a+=1

0 colomn is: [[10]
 [50]
 [21]
 [78]] 

1 colomn is: [[20]
 [60]
 [32]
 [89]] 

2 colomn is: [[30]
 [70]
 [65]
 [48]] 

3 colomn is: [[40]
 [80]
 [45]
 [49]] 

