# Iterating numpy array

In [3]:
# itrarting means=====> meetintg each aary or checking each array
import numpy as np
arr = np.array([10,20,30,40,50,60,70,80,90])
print(arr)

for element in arr:
    print(element)

[10 20 30 40 50 60 70 80 90]
10
20
30
40
50
60
70
80
90


In [16]:
# iterating on two array
two_D = np.array([[10,20,30],[40,50,60]])
print(two_D)
print("\nprinting rows of two array:")
for i in two_D:
    print("\n",i)
    
print("**************************************************")
   
print(" \nprinting each element of of two_D array")
for itr in two_D:
    for itr1 in itr:
        print("\n",itr1)
    

[[10 20 30]
 [40 50 60]]

printing rows of two array:

 [10 20 30]

 [40 50 60]
**************************************************
 
printing each element of of two_D array

 10

 20

 30

 40

 50

 60


In [64]:
# Iterating on scalar array 3-D array
arr = np.array([[[10,20,30],[40,50,60],[70,80,90]]])
print("\nDiamention of array id:",array.ndim)

print("\nprinting each element of the 3-d array")
print("\n*******************************************")
a=1
for x in arr:
    
    for y in x:
        
        for z in y:
            print("\n Element present at location no ",a,"is:",z)
            a+=1
print("\n*******************************************")


Diamention of array id: 3

printing each element of the 3-d array

*******************************************

 Element present at location no  1 is: 10

 Element present at location no  2 is: 20

 Element present at location no  3 is: 30

 Element present at location no  4 is: 40

 Element present at location no  5 is: 50

 Element present at location no  6 is: 60

 Element present at location no  7 is: 70

 Element present at location no  8 is: 80

 Element present at location no  9 is: 90

*******************************************


In [68]:
#prirnting rows of three D array
b=1
for x in arr:
    
    for y in x:
        print("\n The ",b,"row of array is ====>",y)
        b+=1


 The  1 row of array is ====> [10 20 30]

 The  2 row of array is ====> [40 50 60]

 The  3 row of array is ====> [70 80 90]
